package ru.hh.android.plugin.model.enums


enum class CreateModuleBuildTaskType {
    DIRS_STRUCTURE_CREATION,
    MODULE_FILES_CREATION,
    SETTINGS_GRADLE_FILE_MODIFICATION,
    BUILD_GRADLE_DEPENDENCIES_BLOCK_MODIFICATION,
    TOOTHPICK_ANNOTATION_PROCESSING_CONFIG_MODIFICATION,
    MOXY_REFLECTOR_STUB_MODIFICATION
}