name: Publish plugin artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: true

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Publish plugin artifact
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/distributions/*.zip
          fail_on_unmatched_files: true
          tag_name: build-${{ github.run_number }}
          name: Build №${{ github.run_number }}
          draft: false
          prerelease: true
