name: Static analysis
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: detekt
        uses: alaegin/Detekt-Action@v1.23.8
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: tools/static-analysis/detekt/detekt-config.yaml
          detekt_baseline: tools/static-analysis/detekt/detekt-baseline.xml
