name: reviewdog
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: Logs
        run: echo 'GITHUB_WORKSPACE = ${{ github.workspace }}'
      - name: Logs 2
        run: ls ${{ github.workspace }}
      - name: Logs 3
        run: ls ${{ github.workspace }}/build-logic
      - name: Logs 4
        run: ls ${{ github.workspace }}/build-logic/static-analysis-convention
      - name: Logs 5
        run: ls ${{ github.workspace }}/build-logic/static-analysis-convention/rules
      - name: Logs 6
        run: ls ${{ github.workspace }}/build-logic/static-analysis-convention/rules/detekt
      - name: detekt
        uses: alaegin/Detekt-Action@v1.19
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: /${{ github.workspace }}/build-logic/static-analysis-convention/rules/detekt/detekt-config.yml
          detekt_baseline: /${{ github.workspace }}/build-logic/static-analysis-convention/rules/detekt/detekt-baseline.xml