name: reviewdog
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: Clone detekt-config
        run: mv ${{ github.workspace }}/build-logic/static-analysis-convention/rules/detekt-config.yaml ${{ github.workspace }}/detekt-config.yaml
      - name: Clone detekt-baseline
        run: mv ${{ github.workspace }}/build-logic/static-analysis-convention/rules/detekt-baseline.xml ${{ github.workspace }}/detekt-baseline.xml
      - name: detekt
        uses: alaegin/Detekt-Action@v1.19
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: /${{ github.workspace }}/detekt-config.yml
          detekt_baseline: /${{ github.workspace }}/detekt-baseline.xml