name: Static analysis
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: detekt
        uses: alaegin/Detekt-Action@v1.23.4
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: build-logic/static-analysis-convention/rules/detekt/detekt-config.yaml
          detekt_baseline: build-logic/static-analysis-convention/rules/detekt/detekt-baseline.xml
